modLoader="javafml"
loaderVersion="[1,)"

issueTrackerUrl = "${issues}"
license = "MIT"

[[mods]]
displayName = "Borderful"
modId = "borderful"
description = "${description}"
version = "${version}"
authors = "liqw"

logoFile = "assets/borderful/icon.png"

[[mixings]]
config = "borderful.mixins.json"

[[dependencies.borderful]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"